apiVersion: inference.networking.k8s.io/v1
kind: InferencePool
metadata:
  name: "pool-a"
  namespace: grid-system
spec:
  targetPorts:
    - number: 8000
  selector:
    matchLabels:
      app: vllm-vcr
      pool: "pool-a"
  endpointPickerRef:
    name: llmd-epp
    port:
      number: 9002
